 name: my first github action
 on: [push]
 jobs: 
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world!"
            - run: echo "step number 1"
    print-hello-world2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world!"
            - run: echo "step number 2"
