 name: my first github action
 on: [push]
 jobs: 
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v3.0.11
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                    node-version: 16
            - name: install node_module
              run: npm install                    
            - name: build project
              run: npm run build 
            - name: vercel build
              run: npx vercel build 
            - name: vercel debloy
              run: npx vercel deploy --prebuilt

